/**
 * Smart Grid Load Balancer - Main Simulation Runner
 * Academic Concepts: ADSA Unit 2 (Graph Partitioning) + OOPJ (Full 10-Step Lifecycle)
 * 
 * Executes the complete smart grid balancing lifecycle:
 * Step 1: Grid creation
 * Step 2: Zone creation (8 Zones A through H with substations)
 * Step 3: Zone partitioning via ADSA Divide-and-Conquer
 * Step 4: Current-load calculation
 * Step 5: Historical-load generation and CSV export
 * Step 6: Forecast reading (loads forecast.json generated by Python)
 * Step 7: Overload detection
 * Step 8: Load-transfer decision
 * Step 9: Load-transfer simulation
 * Step 10: Updated-load calculation and final grid verification
 */
package smartgrid;

import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.Map;

public class Simulation {
    public static void main(String[] args) {
        System.out.println("================================================================================");
        System.out.println("       SMART GRID LOAD BALANCER - COMPLETE ACADEMIC SIMULATION RUNNER           ");
        System.out.println("       Academic Concepts: ADSA (Unit 2: Graphs & D&C) | OOPJ | Python           ");
        System.out.println("================================================================================");

        try {
            // STEP 1: Grid Creation
            System.out.println("\n[STEP 1] Initializing Smart Grid Graph Topology...");
            Grid grid = new Grid("Metropolitan Regional Smart Microgrid");

            // STEP 2: Zone Creation (8 Zones A to H with Substation composition)
            System.out.println("[STEP 2] Creating 8 Microgrid Zones with localized Transformer Substations...");
            Zone zoneA = new Zone("A", "Zone A (Downtown Core)", 120.0, 110.0, "Sector-1 (North)");
            zoneA.addSubstation(new Substation("SUB-A1", "Central Financial Station", 40.0, 38.0, 132.0, 0.95));
            zoneA.addSubstation(new Substation("SUB-A2", "Civic Center Station", 40.0, 36.0, 132.0, 0.96));
            zoneA.addSubstation(new Substation("SUB-A3", "Commercial Hub Station", 40.0, 36.0, 66.0, 0.94));

            Zone zoneB = new Zone("B", "Zone B (West Tech Park)", 100.0, 55.0, "Sector-1 (North)");
            zoneB.addSubstation(new Substation("SUB-B1", "Silicon Corridor Station", 50.0, 28.0, 132.0, 0.98));
            zoneB.addSubstation(new Substation("SUB-B2", "Server Cluster Substation", 50.0, 27.0, 132.0, 0.97));

            Zone zoneC = new Zone("C", "Zone C (North Industrial)", 150.0, 138.0, "Sector-1 (North)");
            zoneC.addSubstation(new Substation("SUB-C1", "Steel Rolling Station", 50.0, 48.0, 220.0, 0.91));
            zoneC.addSubstation(new Substation("SUB-C2", "Chemical Plant Station", 50.0, 46.0, 220.0, 0.92));
            zoneC.addSubstation(new Substation("SUB-C3", "Foundry Substation", 50.0, 44.0, 132.0, 0.90));

            Zone zoneD = new Zone("D", "Zone D (East Residential)", 110.0, 62.0, "Sector-1 (North)");
            zoneD.addSubstation(new Substation("SUB-D1", "Green Valley Substation", 55.0, 31.0, 66.0, 0.95));
            zoneD.addSubstation(new Substation("SUB-D2", "Sunrise Estate Substation", 55.0, 31.0, 66.0, 0.95));

            Zone zoneE = new Zone("E", "Zone E (South Port Basin)", 130.0, 80.0, "Sector-2 (South)");
            zoneE.addSubstation(new Substation("SUB-E1", "Harbor Container Terminal", 65.0, 40.0, 132.0, 0.94));
            zoneE.addSubstation(new Substation("SUB-E2", "Dry Dock Substation", 65.0, 40.0, 132.0, 0.93));

            Zone zoneF = new Zone("F", "Zone F (Metro Suburb)", 90.0, 50.0, "Sector-2 (South)");
            zoneF.addSubstation(new Substation("SUB-F1", "Hillside Substation", 45.0, 25.0, 66.0, 0.96));
            zoneF.addSubstation(new Substation("SUB-F2", "Valley Park Substation", 45.0, 25.0, 66.0, 0.96));

            Zone zoneG = new Zone("G", "Zone G (Heavy Manufacturing)", 140.0, 122.0, "Sector-2 (South)");
            zoneG.addSubstation(new Substation("SUB-G1", "Automotive Assembly Sub", 70.0, 62.0, 220.0, 0.92));
            zoneG.addSubstation(new Substation("SUB-G2", "Smelter Terminal", 70.0, 60.0, 220.0, 0.91));

            Zone zoneH = new Zone("H", "Zone H (University Campus)", 120.0, 68.0, "Sector-2 (South)");
            zoneH.addSubstation(new Substation("SUB-H1", "Research Reactor Feed Sub", 60.0, 34.0, 132.0, 0.98));
            zoneH.addSubstation(new Substation("SUB-H2", "Hostel District Sub", 60.0, 34.0, 66.0, 0.97));

            // Add all zones to the Grid
            grid.addZone(zoneA);
            grid.addZone(zoneB);
            grid.addZone(zoneC);
            grid.addZone(zoneD);
            grid.addZone(zoneE);
            grid.addZone(zoneF);
            grid.addZone(zoneG);
            grid.addZone(zoneH);

            // Add high-voltage transmission connections (Graph Edges)
            grid.addConnection(new Connection("L-AB", "A", "B", 45.0, 0.04));
            grid.addConnection(new Connection("L-AC", "A", "C", 40.0, 0.05));
            grid.addConnection(new Connection("L-BD", "B", "D", 35.0, 0.06));
            grid.addConnection(new Connection("L-CD", "C", "D", 50.0, 0.03));
            // Inter-sector tie lines (Cut edges)
            grid.addConnection(new Connection("L-CG", "C", "G", 60.0, 0.02));
            grid.addConnection(new Connection("L-DF", "D", "F", 40.0, 0.05));
            // Sector 2 internal lines
            grid.addConnection(new Connection("L-EF", "E", "F", 35.0, 0.04));
            grid.addConnection(new Connection("L-EG", "E", "G", 45.0, 0.04));
            grid.addConnection(new Connection("L-GH", "G", "H", 50.0, 0.03));
            grid.addConnection(new Connection("L-FH", "F", "H", 35.0, 0.05));

            grid.buildAdjacencyMatrix();

            // STEP 3: ADSA Divide-and-Conquer Zone Partitioning
            System.out.println("[STEP 3] Executing ADSA Divide-and-Conquer Graph Partitioning...");
            grid.partitionGridDivideAndConquer();
            System.out.println("         Partition 1 (North Sector): " + grid.getPartitions().get("Sector-1 (North)"));
            System.out.println("         Partition 2 (South Sector): " + grid.getPartitions().get("Sector-2 (South)"));
            System.out.println("         ADSA Cut Edges (Inter-sector links): " + grid.getCutEdges().size() + " transmission lines");

            // STEP 4: Current-Load Calculation
            System.out.println("\n[STEP 4] Calculating Current Grid Metrics & Utilization Factor:");
            double totalLoad = grid.getTotalCurrentLoadMW();
            double totalCapacity = grid.getTotalCapacityMW();
            System.out.printf("         Total Grid Load:     %.2f MW\n", totalLoad);
            System.out.printf("         Total Grid Capacity: %.2f MW\n", totalCapacity);
            System.out.printf("         Aggregate Grid Utilization: %.2f%%\n", (totalLoad / totalCapacity) * 100.0);

            // STEP 5: Historical-Load Generation & CSV Export
            System.out.println("\n[STEP 5] Generating Historical Time-Series Load Data...");
            LoadData loadData = new LoadData();
            String[] times = {"00:00", "04:00", "08:00", "12:00", "16:00", "18:00"};
            for (Zone z : grid.getAllZones()) {
                double base = z.getCurrentLoadMW() * 0.55;
                for (int t = 0; t < times.length; t++) {
                    double factor = 0.55 + (t * 0.09);
                    double val = Math.min(z.getCapacityMW(), Math.round(z.getCurrentLoadMW() * factor * 10.0) / 10.0);
                    loadData.addRecord(new LoadData.Record(
                            "2026-10-04 " + times[t] + ":00",
                            z.getId(), z.getName(), z.getSectorId(),
                            z.getCapacityMW(), val, z.getSubstations().size()
                    ));
                }
            }
            String csvExportPath = "data/load_history.csv";
            loadData.exportToCsv(csvExportPath);
            System.out.println("         [OK] Exported historical time-series to: " + csvExportPath);

            // STEP 6: Read Forecast (Read forecast.json produced by Python)
            System.out.println("\n[STEP 6] Reading Python Short-Term Load Forecast Results (data/forecast.json)...");
            String forecastPath = "data/forecast.json";
            Map<String, Forecast> forecasts = null;
            if (new File(forecastPath).exists()) {
                forecasts = Forecast.loadFromFile(forecastPath);
                System.out.println("         [OK] Successfully loaded Python forecasts for " + forecasts.size() + " zones.");
                for (Zone z : grid.getAllZones()) {
                    Forecast fc = forecasts.get(z.getId());
                    if (fc != null) {
                        z.setForecastedLoadMW(fc.getForecastedLoadMW());
                        z.setRiskLevel(fc.getRiskLevel());
                    }
                }
            } else {
                System.out.println("         [INFO] Python forecast file not found. Generating default predictive model...");
                for (Zone z : grid.getAllZones()) {
                    z.setForecastedLoadMW(Math.round(z.getCurrentLoadMW() * 1.03 * 10.0) / 10.0);
                }
            }

            // STEP 7: Overload Detection
            System.out.println("\n[STEP 7] Detecting Overloaded Zones (Threshold: >= 85.0%)...");
            LoadBalancer balancer = new LoadBalancer(grid);
            List<Zone> overloaded = balancer.detectOverloadedZones(forecasts);
            for (Zone z : overloaded) {
                System.out.printf("         [ALERT] %s | Current: %.1f MW (%.1f%%) | Forecast: %.1f MW (%.1f%%) | Status: %s\n",
                        z.getName(), z.getCurrentLoadMW(), z.getLoadPercentage(),
                        z.getForecastedLoadMW(), z.getForecastPercentage(), z.getRiskLevel());
            }

            // STEP 8 & 9: Load-Transfer Decision and Execution Simulation
            System.out.println("\n[STEP 8 & 9] Computing Safe Load-Transfer Decisions & Executing Simulation...");
            List<LoadTransfer> transfers = balancer.balanceGrid(forecasts);
            for (LoadTransfer tx : transfers) {
                System.out.printf("         [EXECUTED] Shift %.1f MW from Zone %s to Zone %s\n",
                        tx.getAmountMW(), tx.getSourceZoneId(), tx.getDestinationZoneId());
                System.out.printf("                    Zone %s Load: %.1f -> %.1f MW\n",
                        tx.getSourceZoneId(), tx.getSourceLoadBeforeMW(), tx.getSourceLoadAfterMW());
                System.out.printf("                    Zone %s Load: %.1f -> %.1f MW\n",
                        tx.getDestinationZoneId(), tx.getDestLoadBeforeMW(), tx.getDestLoadAfterMW());
                System.out.printf("                    Audit Reason: %s\n", tx.getReason());
            }

            // STEP 10: Updated-Load Calculation and Summary
            System.out.println("\n[STEP 10] Updated Grid Status Post Load Balancing:");
            System.out.println("--------------------------------------------------------------------------------");
            System.out.printf("%-8s %-26s %-12s %-14s %-16s %-14s\n",
                    "Zone", "Name", "Capacity", "Updated Load", "Utilization %", "Status");
            System.out.println("--------------------------------------------------------------------------------");
            for (Zone z : grid.getAllZones()) {
                System.out.printf("%-8s %-26s %-12s %-14s %-16s %-14s\n",
                        z.getId(),
                        z.getName(),
                        String.format("%.1f MW", z.getCapacityMW()),
                        String.format("%.1f MW", z.getCurrentLoadMW()),
                        String.format("%.1f%%", z.getLoadPercentage()),
                        z.getOperationalStatus());
            }
            System.out.println("--------------------------------------------------------------------------------");
            System.out.println("[SUCCESS] Smart Grid Load Balancing Simulation Completed Safely.");
            System.out.println("================================================================================");

        } catch (SmartGridException ex) {
            System.err.println("[ERROR] Smart Grid Execution Failed: " + ex.getMessage());
        } catch (IOException ex) {
            System.err.println("[I/O ERROR] File operations failed: " + ex.getMessage());
        }
    }
}
