/**
 * Smart Grid Load Balancer - Zone Class
 * Academic Concept: OOPJ (Inheritance, Polymorphism, Composition, Encapsulation)
 * 
 * Represents a discrete electrical distribution zone (microgrid node in ADSA graph).
 */
package smartgrid;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public class Zone extends GridEntity {
    private String sectorId; // Partition generated by ADSA Divide-and-Conquer (e.g. Sector-1 North, Sector-2 South)
    private final List<Substation> substations;
    private final List<String> connectedZoneIds;
    private double forecastedLoadMW;
    private String riskLevel;

    public Zone(String id, String name, double capacityMW, double currentLoadMW, String sectorId) {
        super(id, name, capacityMW, currentLoadMW);
        this.sectorId = sectorId;
        this.substations = new ArrayList<>();
        this.connectedZoneIds = new ArrayList<>();
        this.forecastedLoadMW = currentLoadMW;
        this.riskLevel = "NORMAL";
    }

    public void addSubstation(Substation sub) {
        if (sub != null) {
            substations.add(sub);
        }
    }

    public List<Substation> getSubstations() {
        return Collections.unmodifiableList(substations);
    }

    public void addConnectedZone(String neighborZoneId) {
        if (!connectedZoneIds.contains(neighborZoneId)) {
            connectedZoneIds.add(neighborZoneId);
        }
    }

    public List<String> getConnectedZoneIds() {
        return Collections.unmodifiableList(connectedZoneIds);
    }

    public String getSectorId() {
        return sectorId;
    }

    public void setSectorId(String sectorId) {
        this.sectorId = sectorId;
    }

    public double getForecastedLoadMW() {
        return forecastedLoadMW;
    }

    public void setForecastedLoadMW(double forecastedLoadMW) {
        this.forecastedLoadMW = forecastedLoadMW;
        updateRiskClassification();
    }

    public double getForecastPercentage() {
        return (this.forecastedLoadMW / this.capacityMW) * 100.0;
    }

    public String getRiskLevel() {
        return riskLevel;
    }

    public void setRiskLevel(String riskLevel) {
        this.riskLevel = riskLevel;
    }

    public void updateRiskClassification() {
        double maxPct = Math.max(getLoadPercentage(), getForecastPercentage());
        if (maxPct >= 90.0) {
            this.riskLevel = "CRITICAL_OVERLOAD";
        } else if (maxPct >= 80.0) {
            this.riskLevel = "OVERLOAD_WARNING";
        } else {
            this.riskLevel = "NORMAL";
        }
    }

    // Polymorphism: Zone-specific operational status
    @Override
    public String getOperationalStatus() {
        updateRiskClassification();
        return this.riskLevel;
    }

    public boolean isOverloaded() {
        return getLoadPercentage() >= 85.0 || getForecastPercentage() >= 85.0;
    }

    public boolean hasAvailableCapacity(double minimumHeadroomPct) {
        double currentUtil = getLoadPercentage();
        return currentUtil < (100.0 - minimumHeadroomPct);
    }
}
